name: C++ Qt Ubuntu-18.04 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ~/work/EasyGrblSetup/Qt
        key: ${{ runner.os }}-QtCache

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.9.5'
        host: 'linux'
        target: 'desktop'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Create BUILD folder
      run: |
        mkdir ../build
    
    - name: qmake
      working-directory: ../build
      run: qmake ../EasyGrblSetup/EasyGrblSetup.pro
    
    - name: make
      working-directory: ../build
      run: |
        make
        ls -hals
    
    - name: Archive build result
      uses: actions/upload-artifact@v2
      with:
        name: Ubuntu-18.04 Binary
        path: ~/work/EasyGrblSetup/build/EasyGrblSetup
