name: C++ Qt Ubuntu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        include:
          - os: ubuntu-16.04
            qtversion: '5.5'
          - os: ubuntu-18.04
            qtversion: '5.9.5'
          - os: ubuntu-20.04
            qtversion: '5.12.8'

    steps:
    - uses: actions/checkout@v2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qtversion }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qtversion }}
        host: 'linux'
        target: 'desktop'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Create BUILD folder
      run: |
        mkdir ../build
    
    - name: Environment (Ubuntu-16.04)
      if: matrix.os == 'ubuntu-16.04'
      run: echo '::set-env name=LD_LIBRARY_PATH::${{ runner.workspace }}/Qt/5.5/gcc_64/lib'

    - name: qmake
      working-directory: ../build
      run: qmake ${{ github.workspace }}/EasyGrblSetup.pro
          
    - name: make
      working-directory: ../build
      run: make
    
    - name: Archive build result
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} Binary
        path: ${{ runner.workspace }}/build/EasyGrblSetup
