name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
    - name: test home
      run: ls -Rhals /home/runner/
    - name: list qmake
      run: which qmake
    - name: qmake project
      run: qmake -project
    - name: qmake
      run: qmake
    - name: make
      run: make
