name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.9.5'
        host: 'linux'
        target: 'desktop'
    - name: test home
      run: ls -Rhals /home/runner/work
    - name: create BUILD folder
      run: |
        mkdir ../build
        ln -s ../EasyGrblSetup/QLabelClickable.h ../build/QLabelClickable.h
        ln -s ../EasyGrblSetup/QLabelClickable.h ../QLabelClickable.h
    - name: where is DEFAULT
      run: pwd; ls -hals
    - name: where is BUILD
      working-directory: ../build
      run: pwd; ls -hals
    - name: qmake
      working-directory: ../build
      run: |
        ls -hals
        cat ./QLabelClickable.h
        qmake /home/runner/work/EasyGrblSetup/EasyGrblSetup/EasyGrblSetup.pro
        ls -hals
    - name: make
      working-directory: ../build
      run: |
        make
        ls -hals
